class DefaultResponsePage {
    constructor() { 
        const data = document.getElementById("data");
        this.header = data.getElementsByClassName("header")[0];
        this.days = [];
        const rows = data.getElementsByClassName("table")[0].children[0].children;
        for (let i = 0; i < rows.length; i++) {
            const row = rows[i];
            this.days.push({
                date: $('.date', row)[0],
                description: $('.description', row)[0],
                details: $('.details', row)[0],
                warnings: $('.warnings', row)[0],
                temperature: $('.temperature', row)[0],
                main: $(".main", row)[0],

                fillFromSinoptikPage:  function (sinoptikPage) {
                    this.date.innerHTML = sinoptikPage.day.name + ', ' + sinoptikPage.day.date.toLocaleDateString(getLang().code, { year: 'numeric', month: 'numeric', day: 'numeric' });
                    
                    this.temperature.innerHTML = sinoptikPage.day.temperatureMin + ' / ' + sinoptikPage.day.temperatureMax;
                    this.description.innerHTML = sinoptikPage.day.description;
                    this.details.innerHTML = sinoptikPage.day.details;
                    let mainStr = "";
                    for (let i = 0; i < sinoptikPage.day.times.length; i++) {
                        const t = sinoptikPage.day.times[i];
                        mainStr += `<p class="m-0">${t.time} — ${t.temperature} (${t.temperatureSens}), ${t.weather}${(t.chanceOfPrecipitation == '-' ? '' : ' (' + t.chanceOfPrecipitation + '%)')},
                        <span title="${t.windStr}"><i class="fas fa-arrow-circle-up ${t.windClass}"></i> ${t.wind} м/с</span>
                        </p>`
                    }
                    this.main.innerHTML = mainStr;

                    if (sinoptikPage.dayWarnings)
                        this.warnings.innerHTML = page.dayWarnings;
                }
            });
        }
        this.poweredByLink = data.getElementsByClassName("poweredByLink")[0];
    }
}

class PageRender {
    constructor() { }

    static appendHtml(html) {
        const data = $("#data");
        data.append(html);
    }

    static setHtml(html) {
        const data = $("#data");
        data.empty();
        data.html(html);
    }

    static initDefaultResponsePage() {
        const data = $("#data");
        data.empty();
        let html = `
            <div class="header mt-5"></div>
            <table class="table table-striped days">
        `
        for (let i = 0; i < 10; i++) {
            html += `
                <tr>
                    <td class="d-flex flex-wrap">
                        <div class="col-12 col-md-3 my-3 my-md-0 text-center d-flex flex-column justify-content-center">
                            <p class="date font-weight-bold m-0"><i class="fas fa-circle-notch fa-spin"></i></p>
                            <p class="temperature m-0"></p>
                            <p class="description m-0"></p>
                            <p class="warnings m-0 text-danger"></p>
                        </div>
                        <div class="col-12 col-md-9">
                            <p class="main"></p>
                            <p class="details m-0"></p>
                        </div>
                    </td>
                </tr>
            `
        }
        const now = new Date();
        html += `
            </table>
            <p class="text-center text-muted mt-3">
                <small>
                    Source: <a class="poweredByLink" target="_blank" href="https://sinoptik.ua">sinoptik.ua</a>.
                    Generated by <a target="_blank" href="https://github.com/heabijay/sinoptik-dashboard">Sinoptik-Dashboard</a> on
                    ${now.toLocaleDateString(getLang().code, { year: 'numeric', month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit', second: '2-digit' })}.
                </small>
            </p>
        `

        data.html(html);

        return new DefaultResponsePage();
    }

    static setLoading() {  
        const data = $("#data");
        data.empty();
        data.append(`<div class="text-center"><i class="fas fa-sync fa-spin"></i></div>`);
    }

    static setNotFound() {  
        const data = $("#data");
        data.empty();
        data.append(`<div class="text-center text-danger">This city is not found!</div>`);
    }

    static setRegionsUnsupported() {  
        const data = $("#data");
        data.empty();
        data.append(`<div class="text-center text-danger">Regions is unsupported!</div>`);
    }
    
    static clear() {
        const data = $("#data");
        data.empty();
    }
}